//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HsmBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Positions_History
    {
        public int id { get; set; }
        public int member_id { get; set; }
        public int Post_Id { get; set; }
        public System.DateTime DateResumed { get; set; }
        public Nullable<System.DateTime> DateVacated { get; set; }
    }
}
