//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HsmBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMembersList_General
    {
        public int MemberId { get; set; }
        public string Fullname { get; set; }
        public string Part { get; set; }
        public string Split { get; set; }
        public string Friendship_Group { get; set; }
        public string MobileNo { get; set; }
        public string eMail { get; set; }
        public string MaritalStatus { get; set; }
        public int SplitId { get; set; }
        public int PartId { get; set; }
        public string Gender { get; set; }
        public int ClubId { get; set; }
        public string Photo { get; set; }
    }
}
